# Cargo configuration for faster builds

[profile.dev]
# Faster debug builds
debug = 1        # Reduce debug info 
opt-level = 1    # Light optimization for dev builds

[profile.release]
# Keep release optimized but slightly faster linking
lto = "thin"     # Thin LTO instead of full LTO
codegen-units = 1

# Note: LLD linker configuration removed because lld is not installed
# To enable faster linking, install lld: sudo apt install lld
# Then uncomment the following lines:
#
# [target.x86_64-unknown-linux-gnu]
# rustflags = [
#     "-C", "link-arg=-fuse-ld=lld",  # Use LLD linker (much faster)
# ]