# Production Configuration for Claude Usage
# Optimized for performance and reliability

[logging]
level = "INFO"
format = "json"
output = "both"          # Log to both console and file

[processing]
batch_size = 50          # Larger batches for efficiency
parallel_chunks = 8      # More threads for performance
max_retries = 5          # More retries for reliability
progress_interval_mb = 50 # Less frequent progress updates

[memory]
max_memory_mb = 2048     # Higher memory limit for production
buffer_size_kb = 32      # Larger buffers for efficiency
warning_threshold_pct = 90

[dedup]
window_hours = 72        # Longer window for better deduplication
cleanup_threshold = 50000
enabled = true

[output]
json_pretty = false      # Compact JSON for production
include_metadata = false # Minimal metadata for performance
timestamp_format = "%Y-%m-%d %H:%M:%S"

[paths]
claude_home = "~/.claude"
vms_directory = "~/.claude/vms"
log_directory = "/var/log/claude-usage"